version: "3.8"

networks:
  localdev:
    name: localdev

services:
  main-api:
    build: FinanceManager.API/
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - db-server
    networks:
      - localdev

  db-server:
    image: mcr.microsoft.com/mssql/server
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pass1357
      - MSSQL_TCP_PORT=1433
    ports:
      - "1400:1433"
    networks:
      - localdev