name: Deploy

on:
  push:
    branches:
      - master 
      
echo ${{secrets.HEROKU_APP_NAME}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          email: ${{secrets.HEROKU_EMAIL}}  
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          dockerfile_directory: ./FinanceManager.API/
